site_name: Introduction to Docker and GitHub Actions for ML apps
site_author: Drew Silcock, STFC Hartree Centre
copyright: Copyright &copy; STFC Hartree Centre
site_url: https://docker-and-gh-actions-for-ml.training.hartree.dev
repo_name: docker-and-gh-actions-for-ml
repo_url: https://github.com/stfc/docker-and-gh-actions-for-ml
edit_uri: ""

theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
  palette:
    primary: "#1e5df8"
    accent: "#ff5a5a"
  logo: images/ukri.svg
  favicon: images/stfc.png

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - smarty
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized

extra_css:
  - styles.css

extra:
  disqus: docker-and-gh-actions-for-ml
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/drewsilcock
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/drewlhsilcock
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/drewsilcock
