site_name: Go With The Flow
site_author: Drew Silcock, STFC Hartree Centre
copyright: Copyright &copy; 2022 - STFC Hartee Centre
site_url: https://go-with-the-flow.training.hartree.dev
repo_name: go-with-the-flow-code
repo_url: https://gitlab.com/drewsilcock/go-with-the-flow-code
edit_uri: ""

theme:
  name: material
  features:
    - instant
  palette:
    primary: "#1e5df8"
    accent: "#ff5a5a"
  logo: images/ukri.svg
  favicon: images/favicon.ico

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - smarty
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - fontawesome_markdown

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized

extra_css:
  - styles.css

extra:
  disqus: go-with-the-flow
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/drewsilcock
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/drewlhsilcock
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/drewsilcock
