[tool.poetry]
authors = ["Drew Silcock <drew.silcock@stfc.ac.uk>"]
description = "Site for 'Docker and GitHub Actions for ML Apps' workshop."
license = "MIT"
name = "docker-and-gh-actions-for-ml-site"
version = "0.1.0"

[tool.poetry.dependencies]
fontawesome-markdown = "^0.2.6"
mkdocs = "^1.3.0"
mkdocs-git-revision-date-localized-plugin = "^1.0.1"
mkdocs-material = "^8.3.8"
mkdocs-minify-plugin = "^0.5.0"
pymdown-extensions = "^9.5"
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
