[tool.poetry]
name = "ida-cloud-training-docs"
version = "0.1.0"
description = "Documentation for IDA Cloud Training day practical sessions."
authors = ["Drew Silcock <drew.silcock@stfc.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
mkdocs = "^1.1"
mkdocs-material = "^5.1.1"
pymdown-extensions = "^7.1"
fontawesome-markdown = "^0.2.6"
mkdocs-minify-plugin = "^0.3.0"
mkdocs-git-revision-date-localized-plugin = "^0.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
