[tool.poetry]
name = "go-with-the-flow-docs"
version = "0.1.0"
description = "Documentation for Go With the Flow workshop."
authors = ["Drew Silcock <drew.silcock@stfc.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.3.0"
mkdocs-material = "^8.3.8"
pymdown-extensions = "^9.5"
fontawesome-markdown = "^0.2.6"
mkdocs-minify-plugin = "^0.5.0"
mkdocs-git-revision-date-localized-plugin = "^1.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
